### ISSUE TITLE
查询失效了

### ISSUE THREAD

**Issue by skoy03** [yitd/ICP-API#2]
工信部最近更新了,现在查询失效了,能否更新下接口吗?

**Comment by GitHubPangHu** [comment]
官网更新之后加了一个字段，用来区分查询类型的。如果想查其他的，就把对应的类型换掉。把下面这个变量放到15行前面。
//  domain 1  ;  app 6    小程序7  快应用8
`
$serviceType = 1;
`
然后把代码中的15行换成下面的代码即可正常使用。

`$query = json_decode(curl_post("icpAbbreviateInfo/queryByCondition", '{"pageNum":"","pageSize":"","serviceType":"'. $serviceType .'","unitName":"' . $domain . '"}', "application/json;charset=UTF-8", $token));
`
