### ISSUE TITLE
大佬失效了能否更新下

### ISSUE THREAD

**Issue by nfhh** [yitd/ICP-API#3]
大佬失效了能否更新下

**Comment by GitHubPangHu** [comment]
把代码中的15行换成下面的代码即可正常使用。
`$query = json_decode(curl_post("icpAbbreviateInfo/queryByCondition", '{"pageNum":"","pageSize":"","serviceType":"'. $serviceType .'","unitName":"' . $domain . '"}', "application/json;charset=UTF-8", $token));
`

**Comment by GitHubPangHu** [comment]
官网更新之后加了一个字段，用来区分查询类型的。如果想查其他的，就把对应的类型换掉。把下面这个变量放到上面那个代码之前。
//  domain 1  ;  app 6    小程序7  快应用8
`
$serviceType = 1;
`

**Comment by nfhh** [comment]
> 官网更新之后加了一个字段，用来区分查询类型的。如果想查其他的，就把对应的类型换掉。把下面这个变量放到上面那个代码之前。 // domain 1 ; app 6 小程序7 快应用8 `$serviceType = 1;`

大哥厉害啊，可以出个爬虫视频卖课程

**Comment by GitHubPangHu** [comment]
不会啊，我这个只是看别人发帖问这个，我就稍微又研究一下他的代码，发现官网请求多了个参数，自己加了一下，发现又正常了。

**Comment by nfhh** [comment]
> 不会啊，我这个只是看别人发帖问这个，我就稍微又研究一下他的代码，发现官网请求多了个参数，自己加了一下，发现又正常了。

[https://github.com/wongzeon/ICP-Checker](https://github.com/wongzeon/ICP-Checker) 你看这个还去识别拖拽验证码，其实根本不需要，哈哈

**Comment by nfhh** [comment]
> 不会啊，我这个只是看别人发帖问这个，我就稍微又研究一下他的代码，发现官网请求多了个参数，自己加了一下，发现又正常了。

大哥你会不会爬抖音无水印视频地址？

**Comment by GitHubPangHu** [comment]
> > 不会啊，我这个只是看别人发帖问这个，我就稍微又研究一下他的代码，发现官网请求多了个参数，自己加了一下，发现又正常了。
> 
> 大哥你会不会爬抖音无水印视频地址？

我啥都不会，就但是喜欢研究一下这个简单的php而已。我不会爬虫。没学过。

**Comment by GitHubPangHu** [comment]
> 验证码，其实根本不需要，哈哈

可能那个人的思路是跟着网站的流程走的，其实看了此项目代码后，发现，根本用不着。那个验证码，只是前台验证的一个防爬虫手段吧。因为这边是用发请求方式拿数据的，不需要模拟前端查询的方式。

**Comment by nfhh** [comment]
> > 验证码，其实根本不需要，哈哈
> 
> 可能那个人的思路是跟着网站的流程走的，其实看了此项目代码后，发现，根本用不着。那个验证码，只是前台验证的一个防爬虫手段吧。因为这边是用发请求方式拿数据的，不需要模拟前端查询的方式。

666

**Comment by yitd** [comment]
> > 验证码，其实根本不需要，哈哈
> 
> 可能那个人的思路是跟着网站的流程走的，其实看了此项目代码后，发现，根本用不着。那个验证码，只是前台验证的一个防爬虫手段吧。因为这边是用发请求方式拿数据的，不需要模拟前端查询的方式。



> 官网更新之后加了一个字段，用来区分查询类型的。如果想查其他的，就把对应的类型换掉。把下面这个变量放到上面那个代码之前。 // domain 1 ; app 6 小程序7 快应用8 `$serviceType = 1;`

已更新进去
